### ISSUE TITLE
building examples is not documented

### ISSUE THREAD

**Issue by piotrklos-tcl** [cnr-isti-vclab/piccante#14]
I don't know what to install and what to run in order to build the examples. I think that such a piece of documentation belongs in the library. Not everyone who does computer vision knows Qt very well.

**Comment by banterle** [comment]
You don't have to install other libraries to use Piccante in your C++11 projects. If on your platform you do not have openGL you just need to declare PIC_DISABLE_OPENGL.
The library is a header-only library with everything you need in it.

Qt is needed to run examples so there are multi-platform examples, but it is not required to use it!

**Comment by piotrklos-tcl** [comment]
Thanks for getting back to me. 

So the way I understand you is that you confirm that Qt is needed to run examples. I'm already aware of that. The issue I raised is that there is no documentation about how to do it. 

I'm raising this because I'm trying to experiment with Piccante and I would prefer a set of instructions about building stuff rather than trying stuff on my own or asking you for help every time there is a problem.

**Comment by banterle** [comment]
> The issue I raised is that there is no documentation about how to do it.
To run the examples?

> I'm raising this because I'm trying to experiment with Piccante and I would prefer a set of instructions about building stuff rather than trying stuff on my own or asking you for help every time there is a problem.
There is bothering, you can ask when you want.

**Comment by piotrklos-tcl** [comment]
> > The issue I raised is that there is no documentation about how to do it.

> To run the examples?

Yes, to get them to run. Presumably one has to build them first. 

Also, I have an observation about the state of most open-source libraries, that if something isn't documented, it usually either doesn't work or doesn't work as expected or works but breaks down on some basic corner cases. So I think you will naturally catch some issues if you decide to prepare some instructions. 

Anyway, I could really only use Ubuntu instructions, so don't push yourself if that's not something you have time or skill to do.

> 
> > I'm raising this because I'm trying to experiment with Piccante and I would prefer a set of instructions about building stuff rather than trying stuff on my own or asking you for help every time there is a problem.

> There is no bothering, you can ask what you want when you want.

That's great, thanks!
