### ISSUE TITLE
Can I get a raw image?

### ISSUE THREAD

**Issue by WindowsNT** [cnr-isti-vclab/piccante#18]
This library seems promising, one question: Can I import a .hdr file to a raw argb ?
That way I can make a WIC imaging component so Windows can read/write HDR files.

**Comment by banterle** [comment]
Thank you for your question. It is not very clear what you are asking.
Do you mean to convert an HDR image in .hdr format into a DNG with Adobe RGB?

**Comment by WindowsNT** [comment]
No, to convert the .hdr into a raw array of ARGB float values. That way Windows will see it through WIC imaging component.

**Comment by banterle** [comment]
This should be doable. How are values arranged interleaved or by plane? Is there padding?

**Comment by WindowsNT** [comment]
Interlaved, ARGB or RGBA (4 floats) per pixel. There can be padding after each row (stride).
The idea is to make the HDR format visible to all Windows applications.

**Comment by banterle** [comment]
Do you have documentation about the stride, please?

Note that; what can be done in this case is to create a function that converts the current data, and store them in a format as you suggested.
