### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cnr-isti-vclab/piccante#19]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [SegmentationGL](https://github.com/cnr-isti-vclab/piccante/blob/d5eeb149ac4395f4ebb028be4d96850e487138d5/include/gl/tone_mapping/segmentation_tmo_approx.hpp#L72 "Destructor for SegmentationGL")
- [stdVectorClear](https://github.com/cnr-isti-vclab/piccante/blob/d5eeb149ac4395f4ebb028be4d96850e487138d5/include/util/std_util.hpp#L49 "stdVectorClear function")

**Comment by banterle** [comment]
you are perfectly right. However, not all compilers for all platforms support that.

Did you measure a huge bottleneck from those IFs?

**Comment by elfring** [comment]
>However, not all compilers for all platforms support that.

Would you like to point any tools out which are not compliant to the C++ standard according to the linked implementation detail?

:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by banterle** [comment]
>Would you like to point any tools out which are not compliant to the C++ standard according to the linked implementation detail?

Probably old compilers. 

> Would you become interested to use a development tool like “clang-tidy” for corresponding source code adjustments

This aspect will be considered in the future. Probably when moving to smart pointers.

**Comment by elfring** [comment]
>Probably old compilers.

* How far would you like to go back in history?
* Would you dare to restrict development support on C++ standard compliant tools?


>Probably when moving to smart pointers.

:thought_balloon: I would find it helpful if redundant pointer checks could be deleted before occasionally.

**Comment by banterle** [comment]
Do you use this library?

**Comment by banterle** [comment]
>Would you dare to restrict development support on C++ standard compliant tools?
Not now.

**Comment by elfring** [comment]
:crystal_ball: Do you need any configuration checks for incompliant tools (by the software build system)?

**Comment by banterle** [comment]
No, thank you.

**Comment by elfring** [comment]
:crystal_ball: In which time range do you plan to work more with smart pointers?

**Comment by banterle** [comment]
Why?

**Comment by elfring** [comment]
See also (for example):
https://github.com/cnr-isti-vclab/piccante/commit/b225648800a84ecce396d7408583934a6c3cdf0f

**Comment by banterle** [comment]
could you be more specific, please?

**Comment by elfring** [comment]
:eyes: [You adjusted several source code places](https://github.com/cnr-isti-vclab/piccante/commit/b225648800a84ecce396d7408583934a6c3cdf0f "removing extra NULL check") (according to a requested transformation pattern) on 2024-08-22.
