### ISSUE TITLE
hdr_generation_alignment example: HDR output is unexpectedly overexposed

### ISSUE THREAD

**Issue by jamesplease** [cnr-isti-vclab/piccante#20]
### What am I seeing?

When I run the `hdr_generation_alignment` example, the produced HDR image is exposed with intensity at +7/+9 stops for all pixels. A few environments with reasonable tonemapping implemented (Photoshop/Unity) render the output as pure white on SDR screens.

To produce a more balanced result, adjusting the example's exposure in Photoshop by about -10 is required.

### What would I expect to see?

I expected the example to output a more balanced HDR image to serve as a representation of the kinds of "correct" inputs that yield "correct" outputs.

Is this a bug, or is the intended result of this example that the HDR image would be this exposed?

By more balanced, I specifically mean:

- Standard SDR tonemapping would capture detail of the image, rather than showing all white
- A reasonable level of bloom applied on the image would yield the kind of result most people would expect, with bloom most prominent in the sky (at the moment every pixel will be lit up, like the image is of a bright light bulb)

### More info

- Compiled on Windows 11 using `cl \HEsc main.cpp`

**Comment by banterle** [comment]
Piccante given the EXIF information such as shutter speed, aperture, and ISO tries to calibrate the HDR image to have scene-referred values (i.e., cd/m^2); these values are closed as much as possible (with some degree of approximation) to what you would get when measuring using a luminance meter. For example, in the real-world, an office white wall with artificial lighting would have a value of 80.0 cd/m^2.

>>I expected the example to output a more balanced HDR image to serve as a representation of the kinds of "correct"
inputs that yield "correct" outputs.

This "correct" is not physicially correct. HDR is about recording real-world lighting.

>>Standard SDR tonemapping would capture detail of the image, rather than showing all white

It is not clear if you tone mape the image or you just open it on Photoshop.

>>A reasonable level of bloom applied on the image would yield the kind of result most people would expect, with bloom 
>>most prominent in the sky (at the moment every pixel will be lit up, like the image is of a bright light bulb)

There is no bloom filtering as in games.

**Comment by banterle** [comment]
>If I follow what you’re saying, it sounds like HDRis on websites like https://hdri-haven.com/ must have been modified to 
>no longer be physically accurate?

I have no idea of the processing happening there. Re-exposing HDR images or radiance maps is a common practice amonst photographers in order to visualize something on classic monitors and apps. However, this leads to losing important lighting information. It depends on what you want to do with HDR images; if you need physically-based values for lighting simulation then rescaling is not good. There are approximations to guess the original scaling.
