### ISSUE TITLE
Feature request: Thread safe random number generation

### ISSUE THREAD

**Issue by Garoe** [cnr-isti-vclab/piccante#5]
Results are not reproducible when using openMP.

Random number seeding is done with the rand() function for the samplers, like in the [bilateral filter](https://github.com/cnr-isti-vclab/piccante/blob/develop/include/filtering/filter_bilateral_2ds.hpp#L406). When compiling with openMP, the function is called concurrently in each thread, but rand() is not thread safe.

**Comment by banterle** [comment]
it should be fixed now (at least it works on OS X), please have a go to it

**Comment by Garoe** [comment]
Unfortunately it's still giving inconsistent results with the fix. However applying the same procedure in the point [sampler random](https://github.com/cnr-isti-vclab/piccante/blob/develop/include/point_samplers/sampler_random.hpp#L174) does work on my linux machine. Would it make sense to have the seed set to zero there as well?
For the record, a there are more occurrences of rand() which might affect other filters.

**Comment by banterle** [comment]
Ah gosh, thanks for pointing this out. I will handle this "rand" issue from tomorrow, because I am travelling at the moment!

To your knowledge, is std::time thread safe? It could be a good alternative.

**Comment by Garoe** [comment]
I'm sorry but I don't really know about thread safety for time. In the documentation for [std::chrono::system_clock::now](http://www.cplusplus.com/reference/chrono/system_clock/now/), which I've seen used as [seed](http://www.cplusplus.com/reference/random/generate_canonical/) there are no warnings about thread safety. While for [rand()](http://www.cplusplus.com/reference/cstdlib/rand/) it is specified clearly.
However my use case is to get exactly the same image, I need reproducibility for the experiments. Maybe adding a macro to switch between a fixed seed and time could be a good solution.

**Comment by banterle** [comment]
I made some extra changes. Please have a look at them, and let me know what you think about those.

**Comment by Garoe** [comment]
Works like a charm, thanks so much

**Comment by banterle** [comment]
super
