### ISSUE TITLE
LischinskiTMO NaN and file permissions

### ISSUE THREAD

**Issue by Garoe** [cnr-isti-vclab/piccante#9]
Apologies for the continuous creation of issues.  In the photographic operator computation in [LischinskiTMO](https://github.com/cnr-isti-vclab/piccante/blob/develop/include/tone_mapping/lischinski_tmo.hpp#L109) I'm getting a NaN because f and Rz[i] are 0, which causes the tmo to fail and output a black image. The same image works on the Matlab since the initial value for Rz is computed using the MaxQuart function.

Another minor thing is the Lischinski code is that [fstop](https://github.com/cnr-isti-vclab/piccante/blob/develop/include/tone_mapping/lischinski_tmo.hpp#L130) is saved into a file in the parent of the working directory and on linux I might not have permissions to write in that folder. I can make a pull request to write the file on "/tmp/" on linux if that makes sense.

I'm not particularly concerned about this issues as I'm mainly using Reinhard and ExposureFusion.

**Comment by banterle** [comment]
please try it now

**Comment by Garoe** [comment]
Unfortunately the output image is still black when using the attached input file
[testLischinski.hdr.zip](https://github.com/cnr-isti-vclab/piccante/files/208259/testLischinski.hdr.zip)

**Comment by banterle** [comment]
I am on it, CG images are sometimes challenging for TM!

**Comment by banterle** [comment]
Please try it now

**Comment by Garoe** [comment]
Works great, thanks a lot!!
Please note that a few files in samples/build-* and samples/data/output/* seem to have been pushed to the server by mistake.

**Comment by banterle** [comment]
they are all removed, thanks!
